using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Matawaka.Workbench.App;

internal static class Program
{
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };

    public static int Main()
    {
        var root = Path.Combine(Path.GetTempPath(), "matawaka-v0542-publication-probe-" + Guid.NewGuid().ToString("N"));
        try
        {
            var workspace = Path.Combine(root, "Workspace");
            var repo = Path.Combine(workspace, "Workbench");
            Directory.CreateDirectory(Path.Combine(repo, ".git"));
            var matRoot = Path.Combine(repo, "artifacts", "runtime-materialization-v054");
            var receipts = Path.Combine(matRoot, "receipts");
            var transactions = Path.Combine(matRoot, "transactions");
            var leaseDir = Path.Combine(matRoot, "leases", RealHostMaterializationAdmissionVerifierV0542.ExpectedLeaseId);
            Directory.CreateDirectory(receipts);
            Directory.CreateDirectory(transactions);
            Directory.CreateDirectory(leaseDir);

            var runtimeRoot = @"K:\Matawaka\workbench-v0541-materialization-smoke-runtime-001";
            var manifestPath = Path.Combine(root, "runtime-manifest.json");
            var note = $"Generated by Workbench v0.54 materialization lease {RealHostMaterializationAdmissionVerifierV0542.ExpectedLeaseId}; acquisitionReceiptSha256={RealHostMaterializationAdmissionVerifierV0542.ExpectedAcquisitionReceiptSha256}; planSha256={RealHostMaterializationAdmissionVerifierV0542.ExpectedPlanSha256}. MATERIALIZED_VERIFIED is evidence only and grants no execution/model/benchmark/game authority.";
            var manifest = new
            {
                Schema = BoundedRuntimeExecutionV053Service.RuntimeTreeManifestSchema,
                Version = "0.53",
                ManifestId = "runtime-tree-v054-" + RealHostMaterializationAdmissionVerifierV0542.ExpectedLeaseId,
                State = BoundedRuntimeExecutionV053Service.RuntimeTreeVerifiedState,
                RuntimeRoot = runtimeRoot,
                Files = new[]
                {
                    new
                    {
                        RelativePath = RealHostMaterializationAdmissionVerifierV0542.ExpectedExecutableRelativePath,
                        Bytes = RealHostMaterializationAdmissionVerifierV0542.ExpectedMaterializedBytes,
                        Sha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedExecutableSha256,
                        Role = "executable"
                    }
                },
                Note = note
            };
            File.WriteAllText(manifestPath, JsonSerializer.Serialize(manifest, JsonOptions), new UTF8Encoding(false));
            Require(HashFile(manifestPath) == RealHostMaterializationAdmissionVerifierV0542.ExpectedRuntimeManifestSha256,
                "Windows manifest serialization must reproduce exact real-host digest");

            var transactionPath = Path.Combine(transactions, RealHostMaterializationAdmissionVerifierV0542.ExpectedLeaseId + ".json");
            var tx = new
            {
                Schema = BoundedRuntimeTreeMaterializationV054Service.TransactionSchema,
                Version = BoundedRuntimeTreeMaterializationV054Service.Version,
                ObservedAt = DateTimeOffset.Now,
                TransactionId = RealHostMaterializationAdmissionVerifierV0542.ExpectedTransactionId,
                LeaseId = RealHostMaterializationAdmissionVerifierV0542.ExpectedLeaseId,
                RequestId = RealHostMaterializationAdmissionVerifierV0542.ExpectedRequestId,
                State = "MATERIALIZED_VERIFIED",
                AcquisitionReceiptPath = @"K:\Matawaka\Workbench\artifacts\artifact-acquisition-v052\execution.json",
                AcquisitionReceiptSha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedAcquisitionReceiptSha256,
                PlanSha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedPlanSha256,
                Archives = Array.Empty<object>(),
                DestinationRoot = runtimeRoot,
                StagingRoot = (string?)null,
                PlannedFiles = 1,
                PlannedExpandedBytes = 1024L,
                MaterializedFiles = 1,
                MaterializedBytes = 1024L,
                TreeDigestSha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedTreeDigestSha256,
                RuntimeManifestPath = manifestPath,
                RuntimeManifestSha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedRuntimeManifestSha256,
                AuthorityConsumed = true,
                FilesystemMutationPerformed = true,
                ExtractionPerformed = true,
                RootPromoted = true,
                ProcessExecutionPerformed = false,
                NetworkAccessPerformed = false,
                BenchmarkPerformed = false,
                ModelRequestPerformed = false,
                GameAccessPerformed = false,
                FailureClassification = (string?)null,
                NonEffects = Array.Empty<string>(),
                Note = "qualification fixture"
            };
            File.WriteAllText(transactionPath, JsonSerializer.Serialize(tx, JsonOptions), new UTF8Encoding(false));

            var statePath = Path.Combine(leaseDir, "state.json");
            var state = new
            {
                Schema = BoundedRuntimeTreeMaterializationV054Service.LeaseStateSchema,
                Version = BoundedRuntimeTreeMaterializationV054Service.Version,
                LeaseId = RealHostMaterializationAdmissionVerifierV0542.ExpectedLeaseId,
                RequestId = RealHostMaterializationAdmissionVerifierV0542.ExpectedRequestId,
                RequestDigestSha256 = new string('1', 64),
                AcquisitionReceiptPath = @"K:\Matawaka\Workbench\artifacts\artifact-acquisition-v052\execution.json",
                AcquisitionReceiptSha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedAcquisitionReceiptSha256,
                ArtifactIds = new[] { RealHostMaterializationAdmissionVerifierV0542.ExpectedArchiveArtifactId },
                DestinationRoot = runtimeRoot,
                MaxFiles = 4,
                MaxExpandedBytes = 4096L,
                TtlSeconds = 300,
                ExactFileCount = 1,
                ExactExpandedBytes = 1024L,
                PlanSha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedPlanSha256,
                IssuedAt = DateTimeOffset.Now.AddSeconds(-2),
                ExpiresAt = DateTimeOffset.Now.AddMinutes(4),
                MaxCalls = 1,
                RemainingCalls = 0,
                BearerSha256 = new string('2', 64),
                State = "MATERIALIZED_VERIFIED",
                Revoked = false,
                Completed = true,
                Failed = false,
                FailureClassification = (string?)null,
                StagingRoot = (string?)null,
                RuntimeManifestPath = manifestPath,
                RuntimeManifestSha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedRuntimeManifestSha256,
                TreeDigestSha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedTreeDigestSha256,
                StateRevision = 8,
                NonEffects = Array.Empty<string>(),
                Note = "qualification fixture"
            };
            File.WriteAllText(statePath, JsonSerializer.Serialize(state, JsonOptions), new UTF8Encoding(false));

            var validReceipt = BuildReceipt(runtimeRoot, manifestPath, transactionPath, statePath,
                "RUNTIME_TREE_MATERIALIZATION_VERIFIED", false,
                RealHostMaterializationAdmissionVerifierV0542.ExpectedTreeDigestSha256);
            var receiptPath = Path.Combine(receipts, "materialization-mattx-probe.json");
            File.WriteAllText(receiptPath, validReceipt, new UTF8Encoding(false));
            var admission = RealHostMaterializationAdmissionVerifierV0542.ValidateReceiptFile(workspace, receiptPath);
            Require(admission.RequestId == RealHostMaterializationAdmissionVerifierV0542.ExpectedRequestId, "valid admission request");
            Console.WriteLine("PASS exact real-host materialization admission accepted");

            ExpectRefusal(workspace, receiptPath, BuildReceipt(runtimeRoot, manifestPath, transactionPath, statePath,
                "ARTIFACT_ACQUISITION_VERIFIED", false,
                RealHostMaterializationAdmissionVerifierV0542.ExpectedTreeDigestSha256), "UI-wrapper terminal status");
            ExpectRefusal(workspace, receiptPath, BuildReceipt(runtimeRoot, manifestPath, transactionPath, statePath,
                "RUNTIME_TREE_MATERIALIZATION_VERIFIED", true,
                RealHostMaterializationAdmissionVerifierV0542.ExpectedTreeDigestSha256), "process execution mutation");
            ExpectRefusal(workspace, receiptPath, BuildReceipt(runtimeRoot, manifestPath, transactionPath, statePath,
                "RUNTIME_TREE_MATERIALIZATION_VERIFIED", false, new string('0', 64)), "tree digest mutation");

            Console.WriteLine("V0542_PUBLICATION_ADMISSION_PASS");
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex);
            return 1;
        }
        finally
        {
            try { Directory.Delete(root, true); } catch { }
        }
    }

    private static string BuildReceipt(string runtimeRoot, string manifestPath, string transactionPath, string statePath,
        string status, bool processExecution, string treeDigest)
    {
        var receipt = new
        {
            Schema = BoundedRuntimeTreeMaterializationV054Service.ExecutionReceiptSchema,
            Version = BoundedRuntimeTreeMaterializationV054Service.Version,
            ObservedAt = DateTimeOffset.Now,
            TransactionId = RealHostMaterializationAdmissionVerifierV0542.ExpectedTransactionId,
            LeaseId = RealHostMaterializationAdmissionVerifierV0542.ExpectedLeaseId,
            RequestId = RealHostMaterializationAdmissionVerifierV0542.ExpectedRequestId,
            State = "MATERIALIZED_VERIFIED",
            AcquisitionReceiptPath = @"K:\Matawaka\Workbench\artifacts\artifact-acquisition-v052\execution.json",
            AcquisitionReceiptSha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedAcquisitionReceiptSha256,
            PlanSha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedPlanSha256,
            Archives = new[]
            {
                new
                {
                    ArtifactId = RealHostMaterializationAdmissionVerifierV0542.ExpectedArchiveArtifactId,
                    ArchivePath = @"K:\Matawaka\matawaka-workbench-v054-materialization-smoke-v1.zip",
                    ArchiveBytes = RealHostMaterializationAdmissionVerifierV0542.ExpectedArchiveBytes,
                    ArchiveSha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedArchiveSha256,
                    SourceUri = "https://example.invalid/exact.zip"
                }
            },
            RuntimeRoot = runtimeRoot,
            RuntimeManifestPath = manifestPath,
            RuntimeManifestSha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedRuntimeManifestSha256,
            TreeDigestSha256 = treeDigest,
            MaterializedFiles = 1,
            MaterializedBytes = 1024L,
            Files = new[]
            {
                new
                {
                    RelativePath = RealHostMaterializationAdmissionVerifierV0542.ExpectedExecutableRelativePath,
                    Bytes = 1024L,
                    Sha256 = RealHostMaterializationAdmissionVerifierV0542.ExpectedExecutableSha256,
                    Role = "executable"
                }
            },
            TransactionPath = transactionPath,
            TransactionSha256 = HashFile(transactionPath),
            LeaseStatePath = statePath,
            LeaseStateSha256 = HashFile(statePath),
            MaterializationAuthorityConsumed = true,
            FilesystemMutationPerformed = true,
            ExtractionPerformed = true,
            RootPromoted = true,
            ProcessExecutionPerformed = processExecution,
            RuntimeStartPerformed = false,
            BenchmarkPerformed = false,
            ModelRequestPerformed = false,
            GameAccessPerformed = false,
            NetworkAccessPerformed = false,
            NonEffects = Array.Empty<string>(),
            Status = status,
            Note = "qualification fixture"
        };
        return JsonSerializer.Serialize(receipt, JsonOptions);
    }

    private static void ExpectRefusal(string workspace, string path, string content, string role)
    {
        File.WriteAllText(path, content, new UTF8Encoding(false));
        try
        {
            _ = RealHostMaterializationAdmissionVerifierV0542.ValidateReceiptFile(workspace, path);
            throw new InvalidOperationException("Expected admission refusal: " + role);
        }
        catch (InvalidDataException)
        {
            Console.WriteLine("PASS refused " + role);
        }
    }

    private static string HashFile(string path)
    {
        using var stream = File.OpenRead(path);
        return Convert.ToHexString(SHA256.HashData(stream)).ToLowerInvariant();
    }

    private static void Require(bool value, string message)
    {
        if (!value) throw new InvalidOperationException("Probe assertion failed: " + message);
    }
}
